language: cpp

os: linux
dist: xenial
sudo: required
compiler: gcc
addons:
  apt:
    packages:
      - libreadline-dev

before_script:
  python3 -V &&
  git clone https://github.com/epics-base/epics-base.git epics-base --branch R7.0.2 &&
  export EPICS_BASE=$PWD/epics-base &&
  export EPICS_HOST_ARCH=$($EPICS_BASE/startup/EpicsHostArch) &&
  cd epics-base &&
  make &&
  cd .. &&
  echo "epics-base built successfully"

script:
  export EPICS_BASE=$PWD/epics-base &&
  export EPICS_HOST_ARCH=$($EPICS_BASE/startup/EpicsHostArch) &&
  export PATH=$PATH:$EPICS_BASE/bin/$EPICS_HOST_ARCH/ &&
  export EPICS_CA_AUTO_ADDR_LIST=NO &&
  export EPICS_CA_ADDR_LIST=127.255.255.255 &&
  python3 script/build.py &&
  python3 script/test.py
